development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: prelaunchr_development

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: prelaunchr_test
